version: "3.7"
services:
  db:
    build: mysql
    platform: linux/x86_64
    image: mo_db
    container_name: mo_db
    ports:
      - 3306:3306
  app:
    build: mushroom-observer
    command: bash -c "sleep 45 && bundle install && bundle exec rails db:migrate && bundle exec rails lang:update && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: mo_app
    container_name: mo_app
    ports:
      - 3000:3000
    volumes:
      - ./mushroom-observer:/moApp
    depends_on:
      - db
