#!/bin/bash

if [ ! -d mushroom-observer ]; then
    # The --branch arg should be removed once this gets merged to main
    git clone --branch mo-docker git@github.com:MushroomObserver/mushroom-observer.git
    echo Cloned MushroomObserver/mushroom-observer
else
    echo mushroom-observer directory exists
fi

cd mushroom-observer

if [ ! -f config/database.yml ]; then
    cp db/docker/database.yml config
    echo Copied config/database.yml
else
    echo database.yml exists
fi

if [ ! -f config/gmaps_api_key.yml ]; then
    cp config/gmaps_api_key.yml-template config/gmaps_api_key.yml
    echo Copied config/gmaps_api_key.yml
else
    echo gmaps_api_key.yml exists
fi

cd ..

docker-compose build
docker-compose up -d
